异常处理

```java
@Override
@Transactional(rollbackFor = Exception.class)
public void doA(String str) throws Exception {
    try{
       	boolean flag = doB(String param);
        if(!flag){
            throw new Exception(e.getMessage()); 
        }
    }cacth(Exception e){
        TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();
    }
}

private boolean doB(String param) throws Exception{
    boolean flag = true;
    try{
       	//逻辑代码
    }cacth(Exception e){
        flag = false;
    }
    return flag；
}
/**
	以上异常被捕获，@Transactional(rollbackFor = Exception.class)失效，加上
	TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();
	事务会回滚;
	在私有方法doB中，如果try/catch，异常会被捕获==>在外出手动抛异常，回滚事务
*/
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
@Override
@Transactional(rollbackFor = Exception.class)
public void doC(String str) throws Exception {
    try{
       	boolean flag = doC(String param);
        //如果doC()中没有try/catch，就不用手动抛异常
    }cacth(Exception e){
        TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();
    }
}

private boolean doD(int param) throws Exception{
    boolean flag = true;
    if(param>10){
        flag = false;
    }
    return flag；
}
//在私有方法doD中，出现异常方法会抛出异常==>在外层捕获异常，回滚事务
```

